services:
  flask-app:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
    volumes:
      - .:/app

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"

  worker:
    build: .
    command: python worker.py
    depends_on:
      - redis
    volumes:
      - .:/app
